# Generated by Django 5.1 on 2024-08-31 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progess', 'in_progess'), ('success', 'success'), ('failed', 'failed')], default='in_progess', max_length=30)),
                ('webhook_status', models.CharField(choices=[('not_sent', 'not_sent'), ('sent', 'sent')], max_length=30, null=True)),
                ('webhook_request', models.TextField(blank=True, null=True)),
                ('webhook_response', models.TextField(blank=True, null=True)),
                ('webhook_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='image_processing.setting')),
            ],
        ),
        migrations.CreateModel(
            name='SKUItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_processing.processingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('input', 'input'), ('proccessed', 'input')], max_length=30)),
                ('image', models.ImageField(upload_to='images')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_processing.skuitem')),
            ],
        ),
    ]
