# Generated by Django 5.1 on 2024-09-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_images_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrequest',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='processingrequest',
            name='failure_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
